name: Autograding
description: "GitHub Action-based Autograding"
author: "@illinois"
inputs:
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
  path:
    description: An assignment path within the repository.
    required: false
  test_suite:
    description: A test_suite name within the repository.
    default: 'autograding'
  step_summary: 
    description: Boolean describing if a step summary should be generated
    default: false
  all_or_nothing: 
    description: Boolean describing if grade should be calculated using percentages of passed tests or all-or-nothing
    default: false
runs:
  using: "node20"
  main: "./dist/index.js"
